name: infoservice
description: Social service

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.115+115

environment:
  # sdk: '>=2.17.0 <3.0.0' # flutter 3.0.0
  # sdk: '>=2.17.6 <3.0.5' # flutter 3.0.5
  sdk: '>=2.18.0 <3.0.5' # flutter 3.3.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  firebase_core: ^1.22.0
  firebase_messaging: 13.0.1
  firebase_analytics: 9.3.4
  awesome_notifications: ^0.6.21
  #xmpp_plugin: ^2.2.1
  xmpp_plugin:
    path: xmpp_plugin-2.2.3 # custom version
  http: ^0.13.4
  flutter_svg: ^1.0.3
  # https://github.com/Baseflow/flutter-permission-handler/issues/718
  # Granular media permissions https://github.com/Baseflow/flutter-permission-handler/issues/907
  permission_handler: ^11.0.1
  package_info_plus: ^1.4.2
  sqflite: ^2.0.2+1
  cached_network_image: ^3.2.1
  #dash_chat_2: ^0.0.14
  dash_chat_2:
    path: dash_chat_2-0.0.15 # custom version
  #file_picker: ^4.6.1
  file_picker: ^5.2.10
  image_picker: ^0.8.5+3
  # https://github.com/crazecoder/open_file/issues/255
  # xmlns:tools="http://schemas.android.com/tools" to AndroidManifest.xml
  open_file: ^3.3.2
  device_info_plus: ^4.1.3
  record: ^4.4.0
  #material_floating_search_bar: ^0.3.7
  material_floating_search_bar:
    path: material_floating_search_bar-0.3.8 # custom version
  carousel_slider: ^4.1.1
  dio: ^4.0.6
  archive: ^3.3.0
  # android error could not find android-104.5112.03.jar
  # implementation 'com.github.webrtc-sdk:android:104.5112.06' =>
  # implementation 'io.github.webrtc-sdk:android:104.5112.07'
  flutter_webrtc: ^0.9.17
  sip_ua: ^0.5.3
  #flutter_callkit_incoming: ^1.0.2+1
  # https://stackoverflow.com/questions/69650283/open-ios-flutter-app-directly-after-answering-voip-call-from-locked-ios-device
  flutter_callkit_incoming:
    path: flutter_callkit_incoming-1.0.2+2 # custom version
  uuid: ^3.0.6
  all_sensors: ^0.4.2
  #flutter_apns: ^1.5.4
  #chat_composer: ^1.0.3
  chat_composer:
    path: chat_composer-1.0.4 # custom version
  just_audio: ^0.9.28
  url_launcher: ^6.1.6
  contacts_service: ^0.6.3
  ionicons: ^0.1.2 # https://ionicons.ez-connect.net/#/
  flutter_markdown: ^0.6.14
  wakelock: ^0.6.2
  flutter_background_service: ^5.0.1
  sentry_flutter: ^7.9.0
  flutter_easyloading: ^3.0.5
  flutter_app_badger: ^1.5.0
  #android_alarm_manager_plus: ^2.1.4
  appmetrica_plugin: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/contacts_warning.md
    - assets/privacy_policy.md
    - assets/terms_and_conditions.md
    - assets/app_icons/appstore.png
    - assets/app_icons/playstore.png
    - assets/avatars/
    - assets/loading/
    - assets/svg/
    - assets/misc/
    - assets/call/
    - assets/images/

  fonts:
    - family: Funtya
      fonts:
        - asset: assets/fonts/funtya.ttf